services:
  postgres:
    image: postgres:17
    container_name: restaurant-saas-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - restaurant_saas_postgres_data:/var/lib/postgresql/data

volumes:
  restaurant_saas_postgres_data: